### ISSUE TITLE
bug: Creating a new trail mark with `:TrailBlazerNewTrailMark` fails with a Lua error

### ISSUE THREAD

**Issue by miguno** [LeonHeidelbach/trailblazer.nvim#1]
### Did you check docs and existing issues?

- [X] I have read all the trailblazer.nvim docs
- [X] I have searched the existing issues of trailblazer.nvim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

0.8.2 (release)

### Operating system/version

macOS 13.1

### Describe the bug

I tried a fresh installation of the plugin, using its default settings. Attempting to create the first mark fails with the error described further below.

### Steps To Reproduce

1. Install trailblazer, via packer, with the config snippet provided in the README.

```lua
-- Using packer
use({
    "LeonHeidelbach/trailblazer.nvim",
    config = function()
        require("trailblazer").setup({
            -- your custom config goes here
        })
    end,
})
```

2. Reload the packer configuration and run `:PackerInstall`.
3. Restart nvim.
4. Open an arbitrary file as playground for the plugin.
5. Manually run `:TrailBlazerNewTrailMark` or `:TrailBlazerNewTrailMark 1` (note: the default keybind Alt-l didn't work).

This triggers the following error:

```
Error executing Lua callback: ...tart/trailblazer.nvim/lua/trailblazer/trails/actions.lua:48: attempt to perform arithmetic on a nil value
stack traceback:
        ...tart/trailblazer.nvim/lua/trailblazer/trails/actions.lua:48: in function 'new_trail_mark'
        ...k/packer/start/trailblazer.nvim/lua/trailblazer/init.lua:146: in function 'new_trail_mark'
        ...ack/packer/start/trailblazer.nvim/plugin/trailblazer.lua:29: in function <...ack/packer/start/trailblazer.nvim/plugin/trailblazer.lua:29>
```

### Expected Behavior

`:TrailBlazerNewTrailMark` should set a new trail mark, without errors.

**Comment by LeonHeidelbach** [comment]
@miguno This should be fixed now. Simply run a `:PackerSync`. The issue was, that neovim passed an empty table for the cursor position as a default value into the user command which caused the actual cursor position not to be calculated. If the default key binding with the `Alt` key does not work for you, you can simply change it to a different keymap through the configuration table you can pass to the setup function. On macOs for example, mapping the `Alt` key can cause issues.

Can you let me know if this fixes the issue for you?

**Comment by miguno** [comment]
Thank you for the fast reply and fix!  The bug fix works for me after a `:PackerSync` run.
