### ISSUE TITLE
bug: Trail marks persist even when marked text is deleted

### ISSUE THREAD

**Issue by FelixKratz** [LeonHeidelbach/trailblazer.nvim#18]
### Did you check docs and existing issues?

- [X] I have read all the trailblazer.nvim docs
- [X] I have searched the existing issues of trailblazer.nvim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.8.3

### Operating system/version

macOS 13.1

### Describe the bug

Trail marks are not deleted after removing a marked word.

https://user-images.githubusercontent.com/22680421/218118186-efec5895-a3d6-4548-bbac-9ce9e6714c81.mp4

### Steps To Reproduce

1. Create mark in word
2. ciw
3. the mark is still there

### Expected Behavior

Trailmarks are deleted when word is deleted

**Comment by pidgeon777** [comment]
What about making this bug a setting? So that one could choose between removing the mark or keeping it.

But, in case of the removal of the "marked" word, there could be some options for handling the mark:

- Remove it.
- Place it at beginning of the nearest next/previous word.
- Place it at beginning of the line.
- Place it at end of the line.

The most important thing to be kept into account, is that actually if a mark is located at the very end of the line, and a word is deleted there, then the mark seems to persist at a position not accessible at the end of the line, making marks navigation stuck the cursor there once that position is reached (just happened to me after deleting a word).

**Comment by FelixKratz** [comment]
The problematic aspect of this is that the character on the mark persist, see the „c“ in the video.

**Comment by LeonHeidelbach** [comment]
> What about making this bug a setting? So that one could choose between removing the mark or keeping it.
> 
> But, in case of the removal of the "marked" word, there could be some options for handling the mark:
> 
> * Remove it.
> * Place it at beginning of the nearest next/previous word.
> * Place it at beginning of the line.
> * Place it at end of the line.
> 
> The most important thing to be kept into account, is that actually if a mark is located at the very end of the line, and a word is deleted there, then the mark seems to persist at a position not accessible at the end of the line, making marks navigation stuck the cursor there once that position is reached (just happened to me after deleting a word).

@pidgeon777 Making this an option sounds like the best idea. I have also noticed marks getting stuck in positions that are not accessible by the cursor. However, this is actually an issue with Neovims "Extmarks" feature which will probably need fixing on Neovims side as the documentation states that Extmarks should not be placable at coordinates that are outside of the accessible range. There might be a somewhat hacky way to implement this in Lua but it would be best if Neovim would handle those situations natively.

> The problematic aspect of this is that the character on the mark persist, see the „c“ in the video.

@FelixKratz The thing here is that the standard highlight of an Extmark without setting any virtual text did and does not allow for specifying the foreground color. This would sometimes make it very difficult to read the text underneath, however this did in fact have the desired behavior of changing the undelying text dynamically and even removing the highlight altogether once the text was deleted. Here is a screenshot of how this looks:

![no_virt_text_hl](https://user-images.githubusercontent.com/55194243/218128557-05cee463-e01f-4357-b30e-4755960ad491.png)

I might have to implement something custom for this. I did not initallly want to implement custom checks to update the underlying text of trail marks since this will have to be done whenever the "TextChanged" event is triggered, which might have some performance implications but at this point I don't think there is another way to achieve this. I will look into this and see what can be done.

**Comment by LeonHeidelbach** [comment]
I actually tried to delete a line while only using the above text highlighting and this did in fact also fix the issue of marks getting stuck. Turns out this is actually a bug in Neovims native Extmarks code. I will create an issue for this later today.

**Comment by LeonHeidelbach** [comment]
Here is a video that shows everything works as expected when not using virtual text.

https://user-images.githubusercontent.com/55194243/218132114-913af421-3a61-44ef-8472-f46bc0028b9f.mp4

**Comment by pidgeon777** [comment]
> @pidgeon777 Making this an option sounds like the best idea. I have also noticed marks getting stuck in positions that are not accessible by the cursor. However, this is actually an issue with Neovims "Extmarks" feature which will probably need fixing on Neovims side as the documentation states that Extmarks should not be placable at coordinates that are outside of the accessible range. There might be a somewhat hacky way to implement this in Lua but it would be best if Neovim would handle those situations natively.

What if the `virtualedit` option is set to `all`?

**Comment by LeonHeidelbach** [comment]
> What if the `virtualedit` option is set to `all`?

Setting `virtualedit` to either `all` or `onemore` would probably fix this but I am strongly agains setting global editor configuration values inside of a plugin as this might interfere with people's configs. In my opinion, if `virtualedit` is not set, Extmarks should not be placable after the last character of a line. I think this is probably an oversight in Neovims source code.

**Comment by FelixKratz** [comment]
I would always sacrifice readability when I get the correct document content shown in return. I think the mark colors can easily be chosen to provide a proper contrast with the fg colors of highlighted text.

**Comment by LeonHeidelbach** [comment]
Sure but with the current way Neovims Extmarks work, this comes with quite some inconsistency. You might have some highlights that don't play well with your trail mark background and some that do. In general, Extmarks should properly set the foreground color specified in the set highlight group (background colors seem to work just fine), which should also take precident over any other highlighting that might be applied to the text (i.e. Treesitter or similar). I would not want to push a "half baked" solution as demonstrated in my video above that would potentially mess with the readability. However, depending on how quick the Neovim team fixes this issue, I might implement an intermediate solution that uses the "TextChanged" trigger to handle this.

**Comment by pidgeon777** [comment]
@LeonHeidelbach would you consider implementing the proposal of letting a user choose how to handle the deleted word mark? See https://github.com/LeonHeidelbach/trailblazer.nvim/issues/18#issuecomment-1425912143.

**Comment by LeonHeidelbach** [comment]
@pidgeon777 Yes, I think this would be a nice addition. I'll think about a way this could be implemented best.

**Comment by LeonHeidelbach** [comment]
@FelixKratz These (433eb2733d66cb7613881ea3ef0e621473499473, 003ce96b71d576515642e936d7ba42dd577efc2f) should fix your issue without implementing a hacky solution that would tap into the "TextChanged" event.

**Comment by FelixKratz** [comment]
It seems to behave a lot better now, however, there seems to be a problem where the visual indication of the mark disappears while it is still contained in the stack. The next navigation event shows it again:

Repro: dd on marked line

https://user-images.githubusercontent.com/22680421/218432593-e542c006-6117-4eeb-9c54-73425d18d12c.mp4

**Comment by LeonHeidelbach** [comment]
> It seems to behave a lot better now, however, there seems to be a problem where the visual indication of the mark disappears while it is still contained in the stack. The next navigation event shows it again:
> 
> Repro: dd on marked line
> 
>  bug.mp4

@FelixKratz This was somewhat of the intended behavior, since at least for me, I usually don't want to delete the underlying trail mark when I delete a specific word. However, I made some changes, that will now delete trail marks if you delete the entire line or a range of lines containing trail marks, as this is in my opinion is a clear enough indication that the trail marks within that range are no longer needed. A specific trail mark can simply be delted by using the same keybinding for creating a new one on an exisiting one. Also this change luckily did not require using the "TextChanged" event, which would be different if I wanted to implement deleting trail marks when the surrounding word was deleted.
