### ISSUE TITLE
bug: can't see icon in gutter with gitsigns enabled

### ISSUE THREAD

**Issue by nick4tech** [LeonHeidelbach/trailblazer.nvim#22]
### Did you check docs and existing issues?

- [X] I have read all the trailblazer.nvim docs
- [X] I have searched the existing issues of trailblazer.nvim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

0.8.4

### Operating system/version

Macos 13.2

### Describe the bug

First of all, love the plugin!!!! I've always been frustrated with `marks` implementation in neovim, and never really been a fan of Harpoon since it doesn't fit my workflow. Having multiple stacks, allows me to separate my marked files in groups which is something I REALLY needed.

So the bug is that if I'm using git signs and I have edits on the same line as the mark, gitsigns will take over and override the mark icon. Is there anyway to set a priority by plugin on this?

### Steps To Reproduce

1. Add git signs
2. Add trailblazer
3. Edit a line that's version controlled
4. Add a mark on the same line
5. Mark icon is not shown 

### Expected Behavior

I would expect trailblazer to show the mark icon instad of the gitsigns icon, or ideally both!

**Comment by LeonHeidelbach** [comment]
@nick4tech Thank you for the nice feedback! It's always great to hear if a project improves not only one's own workflow and I had the same frustration with the default marks for quite some time :+1:.

The problem that your trail mark signs don't show up when Gitsigns are visible is caused by the set mark priority for GitSigns. By default TrailBlazer sets it's priority to a very high value, namely `10001` so that it overshadows most other plugins. I do in fact use GitSigns myself and did not encounter this behavior as my GitSigns disappear when I add a trail mark to a version controlled line. In their [default configuration](https://github.com/lewis6991/gitsigns.nvim#usage) GitSigns set their `sign_priority` to a value of `6`, which is obviously much lower that the value that I set so all trail marks should overshadow any GitSign symbol. Unfortunately Neovim currently does not support a way of showing the symbols of multiple marks in one line of the sign column and implementing a solution that would enable this behavior would be rather hacky and most likely a performance nightmare if it's supposed to be "responsive".

However, I have just added the option to manually set the trail mark priority to an even higher (or lower) number if necessary through the configuration table 03e4f200e6c7c019beb64aaaeb79695e5ffb4b38. You can now either set the GitSigns priority to a lower value or the trail mark priority to a even higher one. Just be careful, for some reasons Neovim does not like it if you set the priority too high and will just not render anything in addition to some other weird behavior. Let me know if this works for you.
