### ISSUE TITLE
bug: Autoload session does not work

### ISSUE THREAD

**Issue by FelixKratz** [LeonHeidelbach/trailblazer.nvim#30]
### Did you check docs and existing issues?

- [X] I have read all the trailblazer.nvim docs
- [X] I have searched the existing issues of trailblazer.nvim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

0.8.3

### Operating system/version

13

### Describe the bug

The auto load session features appears to be not working at all:

What I do in the video:
* Save the session manually
* Quit nvim
* reopen the file through nnn
* place a mark
* load the session manually

Manual loading works, auto-loading does not work. I am not doing any lazy loading.

https://user-images.githubusercontent.com/22680421/221558122-001320c8-45ea-45b6-aaeb-e4c9ee92bc4d.mp4

### Steps To Reproduce

* Save session
* Close & Reopen file
* No session to be seen

### Expected Behavior

Session is loaded automatically

**Comment by LeonHeidelbach** [comment]
@FelixKratz I almost forgot about this problem, but this is an issue directly connected to the order in which Lazy.nvim loads plugins. Lazy does load the files from the plugin folder first, which currently contain the auto-load functionality. At this point your custom configuration has not yet been applied since the `setup` function has not been called so the default value for this feature will be used (i.e. `false` which disables auto-loading). To resolve this issue, I would probably have to move the auto-load functionality from the plugin folder into the `setup` function itself. There has been a discussion about this issue with @folke before in this issue https://github.com/glepnir/dashboard-nvim/issues/222#issuecomment-1372751949.

**Comment by FelixKratz** [comment]
Why wouldnt you be able to internally call the autoload routine right after setup is called?

**Comment by LeonHeidelbach** [comment]
@FelixKratz This is exactly what I said in my comment above and implemented here 8d5bada8209c62ea98382f3fe44d8e2f32926fb7. Auto-loading sessions should now also be fixed with Lazy.nvim.
