### ISSUE TITLE
bug: Manual session loading errors

### ISSUE THREAD

**Issue by FelixKratz** [LeonHeidelbach/trailblazer.nvim#33]
### Did you check docs and existing issues?

- [X] I have read all the trailblazer.nvim docs
- [X] I have searched the existing issues of trailblazer.nvim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

0.8.3

### Operating system/version

13

### Describe the bug

![Screenshot 2023-02-28 at 11 23 32](https://user-images.githubusercontent.com/22680421/221826478-44bb13b7-5833-441d-aa05-eb38cd43fba5.png)

### Steps To Reproduce

Manually load a session

### Expected Behavior

No error

**Comment by LeonHeidelbach** [comment]
@FelixKratz The error `Vim:E325` is related to an already existing Swap file. This means that a file within your session is already open in another editor instance. The expected behavior should probably not be "No error" but rather a more descriptive error as to what file is already open in another editor. Will look into this later. Related #32.

**Comment by LeonHeidelbach** [comment]
@FelixKratz This should be fixed now add759407d5d0c7ef6f1dd1d5846d614056a56b0.
