### ISSUE TITLE
feature: navigate freely between trails back and forth

### ISSUE THREAD

**Issue by alajmo** [LeonHeidelbach/trailblazer.nvim#44]
### Did you check the docs?

- [X] I have read all the trailblazer.nvim docs

### Is your feature request related to a problem? Please describe.

I want to be able to navigate between trails that I set freely. For instance, if you edit code in 4 locations, then you want to be able to go between those 4 locations unlimited number of times. 

### Describe the solution you'd like

The order of navigation could be one of the folllowing (or both):

- in chronological order (in a single buffer it's given, however when you have multiple files then I suppose it's a bit harder to keep track of which is chronological, perhaps the buffer ordering) 
- the order they were created, this should be simpler I assume

When you reach the end, either allow one to go back to the beginning trail or it should halt (perhaps different key mappings for this, since the functionality depends on the context).

### Describe alternatives you've considered

I tried accomplishing said task using the:

```
                peek_move_next_down = '<A-J>',
                peek_move_previous_up = '<A-K>',
```

mappings, but it doesn't seem to work after I reach the end of the trail. The trails are still there, but I cannot go back and forth.

**Comment by LeonHeidelbach** [comment]
@alajmo Please read the documentation ;). What you describe is in fact exactly what the extension is all about and the functionality is already implemented, with a multitude of different trail mark sort modes. If you are on MacOS, you might have to change the mapping and use a different modifier than the <kbd>alt</kbd> key since this key can be problematic here. You can try to access the QuickFix list to move to a specific mark and try moving from there using the peek motions. What could also have happened is that for some reason one mark got stuck, so you can remove it from the QuickFix list.

**Comment by alajmo** [comment]
Apologies,  it seems my keymaps were the issue, I had it set to:

```
      force_mappings = {
        nv = {
          motions = {
            new_trail_mark = "<M-a>",
            peek_move_next_down = "<M-b>",
            peek_move_previous_up = "<M-n>",
          },
          actions = {
            delete_all_trail_marks = "<M-M>",
          },
        },
```

and for some reason, perhaps due to being the alt key combined with n/b it didn't work properly.  Calling the functions `TrailBlazerPeekMovePreviousUp` seemed to work and so I tried using `<M-w>` / `<M-q>` instead and that worked.
Thanks for a great plugin, just what I was looking for.
