### ISSUE TITLE
feature:  Cycle through marks ?

### ISSUE THREAD

**Issue by Twix53791** [LeonHeidelbach/trailblazer.nvim#49]
### Did you check the docs?

- [X] I have read all the trailblazer.nvim docs

### Is your feature request related to a problem? Please describe.

First, thanks for this amazing plugin! It is exactly what I wanted to marks. I am doing some tests to understand how it works, and I did'nt find any command to cycle through, or mode, or setting? Did I missed something?

### Describe the solution you'd like

I would like to cycle through marks, when `TrailBlazerPeekMovePreviousUp` arrive at the end for example, it loops. It would be usefull or me because I think using few temporary marks to navigate files I edit. So cycle through them will not be confusing and it would let me use a single key binding to cycle.

### Describe alternatives you've considered

Another option, of course, would be to have the possibility of displaying a list of the marks and quickly select one. It is even better maybe, even it is only worthy for few marks probably. Anyway, I saw there is a command `TrailBlazerToggleTrailMarkList` which seems to do that, but for now, it returns me an error. I am gonna try to fix it before asking help on that forum...

### Additional context

PS: by the way, the doc on the main page is a bit verbose and not always clear to my opinion! Personally, I struggle a bit to understand all the trailblazer functionalities.

**Comment by LeonHeidelbach** [comment]
> ### Did you check the docs?
> * [x]  I have read all the trailblazer.nvim docs
> 
> ### Is your feature request related to a problem? Please describe.
> First, thanks for this amazing plugin! It is exactly what I wanted to marks. 

You're welcome :).

>I am doing some tests to understand how it works, and I did'nt find any command to cycle through, or mode, or setting? Did I missed something?
>
> ### Describe the solution you'd like
> I would like to cycle through marks, when `TrailBlazerPeekMovePreviousUp` arrive at the end for example, it loops. It would be usefull or me because I think using few temporary marks to navigate files I edit. So cycle through them will not be confusing and it would let me use a single key binding to cycle.

Adding this will not be a priority since this can be confusing for people who have many trail marks and the trail mark list does exactly what you want.

> ### Describe alternatives you've considered
> Another option, of course, would be to have the possibility of displaying a list of the marks and quickly select one. It is even better maybe, even it is only worthy for few marks probably. Anyway, I saw there is a command `TrailBlazerToggleTrailMarkList` which seems to do that, but for now, it returns me an error. I am gonna try to fix it before asking help on that forum...

The trail mark list is exactly what you are looking for. I recently had someone create an issue where they also reported that they were receiving erros when trying to open the TrailMark list. The issue there was, that the setup function was never called, and thus the plugin was never correctly initialized. Even if you do not want to change any of the default settings, you will have to call the `setup` function through the `config` field of your plugin manager. Let me know if this fixes your problem.

> ### Additional context
> PS: by the way, the doc on the main page is a bit verbose and not always clear to my opinion! Personally, I struggle a bit to understand all the trailblazer functionalities.

The docs are as verbose as possbible on purpose so that you can read about all features in detail without having to review the code itself. However, you will find shorter explanations of all features in the [config](https://github.com/LeonHeidelbach/trailblazer.nvim#%EF%B8%8F-configuration) section.
