### ISSUE TITLE
bug: Duplicated tag "init"

### ISSUE THREAD

**Issue by crivotz** [LeonHeidelbach/trailblazer.nvim#6]
### Did you check docs and existing issues?

- [X] I have read all the trailblazer.nvim docs
- [X] I have searched the existing issues of trailblazer.nvim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.0

### Operating system/version

Debian 11

### Describe the bug

When installed via lazy I receive the following message. All works fine also with this problem
Probably related to multiple `init` header in docs file.

Command related in  lazy.nvim
https://github.com/folke/lazy.nvim/blob/809d67fcf0f6dd5dabdd1c2b88d451cef4695880/lua/lazy/manage/task/plugin.lua#L51

### Steps To Reproduce

1. Install with lazy.nvim

### Expected Behavior

No error ;)

**Comment by LeonHeidelbachHHU** [comment]
@crivotz yes, this will be related to multiple `init` entries in the help tags as the `trails` submodule has its own `init.lua`. Since I automatically generate all help tags through the documentation in the code, I will have to check if there is a way to not have duplicate names for init files in the generated tags using [lemmy-help](https://github.com/numToStr/lemmy-help) later. Interesting though that Packer doesn’t seem to care.

**Comment by crivotz** [comment]
This is the line in packer
https://github.com/wbthomason/packer.nvim/blob/1d0cf98a561f7fd654c970c49f917d74fafe1530/lua/packer/plugin_utils.lua#L80
Maybe it can be useful for resolution
Thanks

**Comment by LeonHeidelbach** [comment]
@crivotz It turns out it was a stupid copy & paste mistake. It should be fixed now. Can you confirm?

**Comment by crivotz** [comment]
> @crivotz It turns out it was a stupid copy & paste mistake. It should be fixed now. Can you confirm?

Solved, thanks ;)
